import { StateOfUsa } from "../types/stateOfUsa";

/** @internal */
export const statesOfUsa: StateOfUsa[] = [
  { name: "Alabama", alpha2Code: "AL" },
  { name: "Alaska", alpha2Code: "AK" },
  { name: "Arizona", alpha2Code: "AZ" },
  { name: "Arkansas", alpha2Code: "AR" },
  { name: "California", alpha2Code: "CA" },
  { name: "Colorado", alpha2Code: "CO" },
  { name: "Connecticut", alpha2Code: "CT" },
  { name: "Delaware", alpha2Code: "DE" },
  { name: "Florida", alpha2Code: "FL" },
  { name: "Georgia", alpha2Code: "GA" },
  { name: "Hawaii", alpha2Code: "HI" },
  { name: "Idaho", alpha2Code: "ID" },
  { name: "Illinois", alpha2Code: "IL" },
  { name: "Indiana", alpha2Code: "IN" },
  { name: "Iowa", alpha2Code: "IA" },
  { name: "Kansas", alpha2Code: "KS" },
  { name: "Kentucky", alpha2Code: "KY" },
  { name: "Louisiana", alpha2Code: "LA" },
  { name: "Maine", alpha2Code: "ME" },
  { name: "Maryland", alpha2Code: "MD" },
  { name: "Massachusetts", alpha2Code: "MA" },
  { name: "Michigan", alpha2Code: "MI" },
  { name: "Minnesota", alpha2Code: "MN" },
  { name: "Mississippi", alpha2Code: "MS" },
  { name: "Missouri", alpha2Code: "MO" },
  { name: "Montana", alpha2Code: "MT" },
  { name: "Nebraska", alpha2Code: "NE" },
  { name: "Nevada", alpha2Code: "NV" },
  { name: "New Hampshire", alpha2Code: "NH" },
  { name: "New Jersey", alpha2Code: "NJ" },
  { name: "New Mexico", alpha2Code: "NM" },
  { name: "New York", alpha2Code: "NY" },
  { name: "North Carolina", alpha2Code: "NC" },
  { name: "North Dakota", alpha2Code: "ND" },
  { name: "Ohio", alpha2Code: "OH" },
  { name: "Oklahoma", alpha2Code: "OK" },
  { name: "Oregon", alpha2Code: "OR" },
  { name: "Pennsylvania", alpha2Code: "PA" },
  { name: "Rhode Island", alpha2Code: "RI" },
  { name: "South Carolina", alpha2Code: "SC" },
  { name: "South Dakota", alpha2Code: "SD" },
  { name: "Tennessee", alpha2Code: "TN" },
  { name: "Texas", alpha2Code: "TX" },
  { name: "Utah", alpha2Code: "UT" },
  { name: "Vermont", alpha2Code: "VT" },
  { name: "Virginia", alpha2Code: "VA" },
  { name: "Washington", alpha2Code: "WA" },
  { name: "West Virginia", alpha2Code: "WV" },
  { name: "Wisconsin", alpha2Code: "WI" },
  { name: "Wyoming", alpha2Code: "WY" }
]